# Name of workflow
name: main-check

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.3']

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v5
        # Step's name
      - name: Set up PHP ${{ matrix.php-versions }}
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: ${{ matrix.php-versions }}

      - name: Set up project
        # Install project
        run: make setup

      - name: Run linter
        # Run Linter
        run: make lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository }}:latest